name: Run lint on CocoaPods specifications

on:
  workflow_dispatch:
  push:
    tags:
      - 'CocoaPods-v[0-9]+.[0-9]+.[0-9]+'
      - 'CocoaPods-v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  macos:
    strategy:
      matrix:
        element:
          - xcode: '14.3'
            machine: macos-13
            
    runs-on: ${{ matrix.element.machine }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.element.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.element.xcode }}.app
      - name: Lint Numberick-NBKCoreKit.podspec
        run: |
          pod lib lint Numberick-NBKCoreKit.podspec \
            --allow-warnings \
            --fail-fast
          echo "SPEC_DEPENDENCIES=Numberick-NBKCoreKit.podspec," >> "$GITHUB_ENV"
      - name: Lint Numberick-NBKDoubleWidthKit.podspec
        run: |
          pod lib lint Numberick-NBKDoubleWidthKit.podspec \
            --allow-warnings \
            --fail-fast \
            --include-podspecs=\{$SPEC_DEPENDENCIES\}
          echo "SPEC_DEPENDENCIES=${SPEC_DEPENDENCIES}Numberick-NBKDoubleWidthKit.podspec," >> "$GITHUB_ENV"
      - name: Lint Numberick.podspec
        run: |
          pod lib lint Numberick.podspec \
            --allow-warnings \
            --fail-fast \
            --include-podspecs=\{$SPEC_DEPENDENCIES\}
